# Generated by Django 2.1.1 on 2018-09-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_trial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trial',
        ),
    ]
